# All makefile fragments assume that $(srcdir) points to the gcc
# directory, not the language subdir
srcdir = /home/simon/work/goldilocks/tmp/work-shared/gcc-5.2.0-r0/gcc-5.2.0/gcc
-include ./gcc-interface/Makefile
-include ../gcc-interface/Makefile
